extern crate specter;

fn main() {
	let mut nioe = Nioe::new();
	nioe.execute();
	
		/////////////////////////////////////////////////////////////////////////////////
		//NOTE: this block is strictly for debugging purposes and is generated by Specter
		specter::debug();
		loop {}
		/////////////////////////////////////////////////////////////////////////////////
}
pub struct Nioe {
	pub print_output_queue: Vec<print>
}
impl Nioe {
	pub fn new() -> Self {
		return Self{
			print_output_queue: vec![],
		};
	}
	pub fn execute(&mut self) {
		//TODO: trigger execution of nodes with a 'silent' input
	}
}
pub struct print {}